---
title: "Clase 1"
author: "Diego A. Bohórquez"
date: "3/9/2020"
output: html_document
---

## Práctica 1

# {.tabset .tabset-pills}

```{r setup, warning=FALSE, message=FALSE, echo=FALSE}

library(readxl)
library(reshape2)
library(dplyr)
library(e1071)
library(Hmisc)
library(inspectdf) #este no lo tienen
library(funModeling) #este no lo tienen
library(VIM) #este no lo tienen
library(stringr)
library(ggplot2)
library(directlabels)
library(scales)
library(ggthemes)

descriptivas<- function(x){data.frame("MEDIDA"=c("Observaciones", "Mínimo", "1er Q", "Media", "Mediana", "Desv Est", "3er Q", "Máximo", "Asimetría", "Curtosis", "atípico leve<", "atípico leve>","atípico extremo<","atípico extremo>", "Err Est Media", "IC(95%) Media Up", "IC(95%) Media Down"),"VALOR"=format(c(length(na.omit(x)), min(na.omit(x)), quantile(na.omit(x), prob=0.25), mean(na.omit(x)), median(na.omit(x)), sd(na.omit(x)), quantile(na.omit(x), prob=0.75), max(na.omit(x)), skewness(na.omit(x)), kurtosis(na.omit(x)), (2.5*quantile(na.omit(x),prob=0.25)-1.5*quantile(na.omit(x), prob=0.75)),(2.5*quantile(na.omit(x),prob=0.75)-1.5*quantile(na.omit(x), prob=0.25)),(4*quantile(na.omit(x),prob=0.25)-3*quantile(na.omit(x), prob=0.75)),(4*quantile(na.omit(x),prob=0.75)-3*quantile(na.omit(x), prob=0.25)), ((sd(na.omit(x))/sqrt(length(na.omit(x))))), (mean(na.omit(x))+1.96*(sd(na.omit(x))/sqrt(length(na.omit(x))))), (mean(na.omit(x))-1.96*((sd(na.omit(x))/sqrt(length(na.omit(x))))))), scientific = F))}
#FUNCIÓN PARA ESTADÍSTICAS DESCRIPTIVAS PARA VARIABLES CONTINUAS

descriptivas2<-function(Continua,Categorías){
  x1=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){length(na.omit(x))})
  names(x1)=c("Categoría","Obs")
  x2=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){min(na.omit(x))})
  names(x2)=c("Categoría","Mínimo")
  x3=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){quantile(na.omit(x), prob =0.25)})
  names(x3)=c("Categoría","1er Q")
  x4=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){median(na.omit(x))})
  names(x4)=c("Categoría","Mediana")
  x5=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){mean(na.omit(x))})
  names(x5)=c("Categoría","Media")
  x6=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){quantile(na.omit(x), prob =0.75)})
  names(x6)=c("Categoría","3er Q")
  x7=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){max(na.omit(x))})
  names(x7)=c("Categoría","Máximo")
  x8=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){sd(na.omit(x))})
  names(x8)=c("Categoría","Desv Est")
  x9=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){skewness(na.omit(x))})
  names(x9)=c("Categoría","Asimetría")
  x10=aggregate.data.frame(Continua, by=list(Categorías), FUN=function(x){kurtosis(na.omit(x))})
  names(x10)=c("Categoría","Curtosis")
  cbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10)[,-seq(3,19,2)]
}
#FUNCIÓN PARA ESTADÍSTICAS DESCRIPTIVAS PARA VARIABLES CONTINUAS EN SUBMUESTRAS
  
tabla_freq<- function(x,total=1,na="ifany"){
  if (total==1) {
    M=data.frame("Categoría"=table(x, useNA = na), "Rel"=prop.table(table(x,useNA = na)))[,-3]
    names(M)=c("Categoría","Freq. Abs.","Freq. Rel.")
    M$Categoría=as.character(M$Categoría)
    M[nrow(M)+1,]=c("Total",sum(M$`Freq. Abs.`),sum(M$`Freq. Rel.`))
    M$`Freq. Rel.`=as.numeric(M$`Freq. Rel.`)
    M$`Freq. Abs.`=as.numeric(M$`Freq. Abs.`)
    M
  } else{
    M=data.frame("Categoría"=table(x, useNA = na), "Rel"=prop.table(table(x,useNA = na)))[,-3]
    names(M)=c("Categoría","Freq. Abs.","Freq. Rel.")
    M
  }
}
#FUNCIÓN PARA ESTADÍSTICAS DESCRIPTIVAS PARA VAR DISCRETAS

tabla_freq2<-function(x,y,na="ifany",prop=0, suma=c("filas","col")){
  if (prop==0) {
    M=as.data.frame.matrix(table(x, y, useNA = na))
    M$Categoría=row.names(M)
    rownames(M)=NULL
    M=M[,c(ncol(M),1:ncol(M)-1)]
    M$Categoría=as.character(M$Categoría)
    M[nrow(M)+1,]=c("Total",colSums(M[,2:ncol(M)]))
    M[,2:ncol(M)]=sapply(M[,2:ncol(M)], as.numeric)
    M$Total=rowSums(M[,2:ncol(M)])
    M
  } else if (prop==1 & suma=="filas") {
    M=as.data.frame.matrix(table(x, y, useNA = na))
    M$Categoría=row.names(M)
    rownames(M)=NULL
    M=M[,c(ncol(M),1:ncol(M)-1)]
    M$Categoría=as.character(M$Categoría)
    M[nrow(M)+1,]=c("Total",colSums(M[,2:ncol(M)]))
    M[,2:ncol(M)]=sapply(M[,2:ncol(M)], as.numeric)
    M$Total=rowSums(M[,2:ncol(M)])
    for (i in 2:ncol(M)) {
      M[,i]=M[,i]/M[,ncol(M)]
    }
    M
  } else {
    M=as.data.frame.matrix(table(x, y, useNA = na))
    M$Categoría=row.names(M)
    rownames(M)=NULL
    M=M[,c(ncol(M),1:ncol(M)-1)]
    M$Categoría=as.character(M$Categoría)
    M[nrow(M)+1,]=c("Total",colSums(M[,2:ncol(M)]))
    M[,2:ncol(M)]=sapply(M[,2:ncol(M)], as.numeric)
    M$Total=rowSums(M[,2:ncol(M)])
    for (i in 1:nrow(M)) {
      M[i,2:ncol(M)]=M[i,2:ncol(M)]/M[nrow(M),2:ncol(M)]
    }
    M 
  }
}

```



## Carga de datos

```{r carga_datos}
base=read_excel("base_clientes.xlsx")
str(base)
```

## Detección de anomalias

```{r anomalias}

#### formato no coincide
base$custid=factor(base$custid)

table(base$sex)
base$sex=factor(base$sex, labels=c("Femenino","Masculino"))
table(base$sex)  

table(base$is.employed)
base$is.employed=factor(base$is.employed, labels = c("No","Sí"))

base$marital.stat=factor(base$marital.stat)

base$health.ins=factor(base$health.ins, labels = c("No","Sí"))

base$housing.type=factor(base$housing.type)

table(base$vehicle)
base$vehicle=factor(base$vehicle,levels=c("YES","NO"), labels = c("Sí","No"))

tabla_freq(base$age)
base$age=as.numeric(base$age)

tabla_freq(base$state.of.res)
str(base)  

### duplicados
tabla_freq(duplicated(base))

duplicados=base[duplicated(base$custid),]

duplicados_total=base[base$custid %in% duplicados$custid,]

ids=tabla_freq(base$custid)

base=base[!duplicated(base),]

### campos vacios
summary(base)
describe(base)
tabla_freq(is.na(base$sex))

tabla=inspect_na(base)
df_status(base)
aggr(base,numbers=T, prop=T,sortVars = T,cex.axis = 0.7)

# conteo de nas por filas
base$conteo_na=rowSums(is.na(base))
# borrar al individuo
base=base[base$conteo_na<5,]

tabla_freq(base$is.employed)
tabla_freq2(base$is.employed, base$sex)

#corrección de na's num.vehicles
tabla_freq2(base$num.vehicles, base$vehicle)
base$num.vehicles[is.na(base$num.vehicles)]=0
tabla_freq(base$num.vehicles)
aggr(base,numbers=T, prop=F,sortVars = T,cex.axis = 0.7)

#base final
base=subset(base, select = -c(is.employed))
aggr(base,numbers=T, prop=F,sortVars = T,cex.axis = 0.7)

### datos atípicos
tabla_freq(base$num.vehicles)
boxplot(base$annual_incomeUSD)
hist(base$annual_incomeUSD)

descriptivas(base$annual_incomeUSD)
ggplot(base, aes(y=annual_incomeUSD))+
  geom_boxplot(fill="brown")+
  labs(y="Ingreso anual ($USD)")+
  scale_y_continuous(labels=dollar)+
  theme_base()+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())+
  ggtitle("Distribución del ingreso anual ($USD)")

ggplot(base, aes(x=annual_incomeUSD))+
  geom_histogram(fill="brown")+
  labs(x="Ingreso anual ($USD)")+
  scale_x_continuous(labels=dollar)+
  theme_base()+
  ggtitle("Distribución del ingreso anual ($USD)")

descriptivas(base$age)
ggplot(base, aes(y=age))+
  geom_boxplot(fill="brown")+
  labs(y="Edad")+
  theme_base()+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())+
  ggtitle("Distribución de la edad")

ggplot(base, aes(x=age))+
  geom_histogram(fill="brown")+
  labs(x="Edad")+
  theme_base()+
  ggtitle("Distribución de la edad")

boxplot(base$age)$out
atipicos=base[base$age %in% boxplot(base$age)$out,]

base$age[base$age<1 | base$age>150]=NA
base$age[base$age %in% boxplot(base$age)$out]=NA
descriptivas(base$age)

### errores de digitación
summary(base)
tabla_freq(base$state.of.res)

#eliminar espacios en blanco
base$state.of.res=str_trim(base$state.of.res)

#llevar todo a mayúsculas
base$state.of.res=toupper(base$state.of.res)
tabla_freq(base$state.of.res)

#corregir los nombres
base$state.of.res[base$state.of.res=="ARIZO"]="ARIZONA"
base$state.of.res[base$state.of.res=="NEWYORK"]="NEW YORK"

#### valores inválidos
descriptivas(base$annual_incomeUSD)
tabla_freq(base$annual_incomeUSD<0)

base$annual_incomeUSD[base$annual_incomeUSD<0]=NA

#### valores INCOSISTENTES
tabla_freq2(base$vehicle,base$num.vehicles)

inconsistente=base[base$num.vehicles>0 & base$vehicle=="No",]

```

## Variables nuevas

```{r var_nuevas}
tabla_freq(base$housing.type)

base$dueño=ifelse(base$housing.type=="Homeowner free and clear" | base$housing.type=="Homeowner with mortgage/loan","Sí","No")
tabla_freq(base$dueño)

base$rango_edad=cut(base$age, breaks=c(0,30,45,60,100))
tabla_freq(base$rango_edad)

```